services:
  user-service:
    build: ./user_service
    networks:
      - backend
    ports:
      - "8001:8001"
  
  product-service:
    build: ./product_service
    networks:
      - backend
    ports:
      - "8002:8002"
  payment-service:
    build: ./payment_service
    networks:
      - backend
    ports:
      - "8003:8003"  
  order-service:
    build: ./order_service
    networks:
      - backend
    ports:
      - "8004:8004"

networks:
  backend:
    driver: bridge
