services:
  user-service:
    build: ../app/user_service
    networks:
      - backend
    ports:
      - "8001:8001"
  
  product-service:
    build: ../app/product_service
    networks:
      - backend
    ports:
      - "8002:8002"
  payment-service:
    build: ../app/payment_service
    networks:
      - backend
    ports:
      - "8003:8003"  
  order-service:
    build: ../app/order_service
    networks:
      - backend
    ports:
      - "8004:8004"

networks:
  backend:
    driver: bridge
