services:
  user_service:
    build: ./user_service
    ports:
      - "8001:8001"
  
  product_service:
    build: ./product_service
    ports:
      - "8002:8002"
  
  order_service:
    build: ./order_service
    ports:
      - "8003:8003"

  payment_service:
    build: ./payment_service
    ports:
      - "8004:8004"