
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadvisor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cadvisor
  template:
    metadata:
      labels:
        app: cadvisor
    spec:
      containers:
        - name: cadvisor
          # image: google/cadvisor:latest
          image: gcr.io/cadvisor/cadvisor:v0.49.2
          ports:
            - containerPort: 8080
          securityContext:
            privileged: true
          volumeMounts:
            - name: rootfs
              mountPath: /rootfs
              readOnly: true
            - name: docker-sock
              mountPath: /var/run/docker.sock
              readOnly: true
            - name: sys
              mountPath: /sys
              readOnly: true
            - name: var-lib-docker
              mountPath: /var/lib/docker
              readOnly: true
            - name: dev-disk
              mountPath: /dev/disk
              readOnly: true
      volumes:
        - name: rootfs
          hostPath:
            path: /
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: sys
          hostPath:
            path: /sys
        - name: var-lib-docker
          hostPath:
            path: /var/lib/docker/
        - name: dev-disk
          hostPath:
            path: /dev/disk/
---
apiVersion: v1
kind: Service
metadata:
  name: cadvisor
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: cadvisor