apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 2.15.0 # Check for latest version
  name: kube-state-metrics
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-state-metrics
    spec:
      containers:
      - image: registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.15.0 # Check for latest version
        name: kube-state-metrics
        ports:
        - containerPort: 8081
          name: http-metrics
        - containerPort: 8082
          name: telemetry
        securityContext:
          runAsUser: 65534
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: kube-state-metrics
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 2.15.0 # Check for latest version
  name: kube-state-metrics
  # namespace: kube-system
spec:
  ports:
  - name: http-metrics
    port: 8081
    protocol: TCP
    targetPort: http-metrics
  - name: telemetry
    port: 8082
    protocol: TCP
    targetPort: telemetry
  selector:
    app.kubernetes.io/name: kube-state-metrics
