apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: kube-system
  name: prometheus-kube-state-metrics
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: Role
  name: prometheus-kube-state-metrics
  apiGroup: rbac.authorization.k8s.io