apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: kube-system
  name: prometheus-kube-state-metrics
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch"]